version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: stone-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: starstone-ecommerce
      MYSQL_USER: su
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    networks:
      - stone-network-ecommerce

  redis:
    image: redis:latest
    container_name: stone-redis
    ports:
      - "6379:6379"
    networks:
      - stone-network-ecommerce

  application:
    image: ecommerceservice:1.0
    container_name: stone-app-service
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - stone-network-ecommerce

networks:
  stone-network-ecommerce:
    driver: bridge
